 server: 
  port: 8081
  
  
 spring:  
  datasource:  
    url: jdbc:mysql://39.108.72.49:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: zaq12WSX
    


 multipart:
  max-file-size: 100Mb
  max-request-size: 1000Mb
